
CREATE DATABASE LEARN_PRO;
USE LEARN_PRO;
CREATE TABLE USERS(
	id MEDIUMINT AUTO_INCREMENT,
	NAME CHAR(255),
	EMAIL CHAR(255),
	PHONE CHAR(255),
	PASSWORD CHAR(255),
	STATUS CHAR(255),
	PRIMARY KEY(id)
);
CREATE TABLE MESSAGE(
	id MEDIUMINT AUTO_INCREMENT,
	ID_OUT char(255),
	ID_PUT char(255),
	MESSAGE CHAR(255),
	PRIMARY KEY(id)
);



CREATE TABLE Academic_training(
	id MEDIUMINT AUTO_INCREMENT,
	NAME CHAR(255),
	PRIMARY KEY(id)


);

CREATE TABLE PROFFESOR(
	id MEDIUMINT AUTO_INCREMENT,
	Academic_training CHAR(255),
	PROFFESOR CHAR(255),
	SEMESTER CHAR(255),
	THEME CHAR(255),
	QUALIFICATION CHAR(255),
	COMMENTS CHAR(255),
	PRIMARY KEY(id)


);